-- AlterTable
ALTER TABLE IF EXISTS "order_items" ADD COLUMN IF NOT EXISTS "primaryImage" TEXT;
ALTER TABLE IF EXISTS "order_items" ADD COLUMN IF NOT EXISTS "salePrice" DOUBLE PRECISION;
ALTER TABLE IF EXISTS "order_items" ADD COLUMN IF NOT EXISTS "modelNumber" TEXT;
